//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucenemvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MultiSite_GangGuanEntities : DbContext
    {
        public MultiSite_GangGuanEntities()
            : base("name=MultiSite_GangGuanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Products_SellOffer> Products_SellOffer { get; set; }
        public virtual DbSet<Products_SellOffer_Detail> Products_SellOffer_Detail { get; set; }
    }
}
