//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucenemvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_SellOffer
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryPath { get; set; }
        public string CategoryName { get; set; }
        public string UserCategorys { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public Nullable<byte> BizType { get; set; }
        public Nullable<double> AmountOnSale { get; set; }
        public string SysAttr { get; set; }
        public string CusAttr { get; set; }
        public string SpecAttr { get; set; }
        public Nullable<byte> Unit { get; set; }
        public Nullable<byte> PriceUnit { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string PriceRanges { get; set; }
        public Nullable<double> OfferWeight { get; set; }
        public Nullable<int> TermOfferProcess { get; set; }
        public Nullable<byte> QuotationMethod { get; set; }
        public Nullable<int> BeginAmount { get; set; }
        public string Deliveryterm { get; set; }
        public string Packaging { get; set; }
        public string ImageList { get; set; }
        public Nullable<int> SendGoodsId { get; set; }
        public string Summary { get; set; }
        public Nullable<byte> InfoType { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string PageUrl { get; set; }
        public Nullable<byte> QualityLevel { get; set; }
        public Nullable<bool> IsSkuTradeSupported { get; set; }
        public Nullable<int> InquireNum { get; set; }
        public string Guid { get; set; }
        public Nullable<long> RefurbishTime { get; set; }
        public Nullable<int> Favourites { get; set; }
        public string Initial { get; set; }
        public Nullable<bool> IsSkuOffer { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<System.DateTime> LastRepostTime { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<byte> IsChecked { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string CheckMessage { get; set; }
        public Nullable<byte> InfoStatus { get; set; }
        public string GoodsProvince { get; set; }
        public string GoodsCity { get; set; }
    }
}
